fix problem with ansible

diff --git a/image/Dockerfile copy.ubi9 b/image/Dockerfile copy.ubi9
--- a/image/Dockerfile copy.ubi9
+++ b/image/Dockerfile copy.ubi9
@@ -9,9 +9,10 @@ LABEL maintainer="IBM Sterling Devops Community" \
 ENV HELM_VERSION=3.16.3 \
     IBMPAK_VERSION=1.21.1 \
     IBMCLI_VERSION=2.40.0 \
-    HOME=/opt/app-root/src \
-    ANSIBLE_CONFIG=/opt/app-root/src/ansible-ibm-sterling/ansible.cfg \
-    PATH="/opt/app-root/src:/usr/local/bin:${PATH}" \
+    HOME=/app-root \
+    ANSIBLE_CONFIG=/app-root/ansible-ibm-sterling/ansible.cfg \
+    PATH="/app-root:/usr/local/bin:${PATH}" \
+    VIRTUAL_ENV_DISABLE_PROMPT=1 \
     PYTHONWARNINGS="ignore:Unverified HTTPS request" \
     LANG=en_US.UTF-8 \
     LC_ALL=en_US.UTF-8 \
@@ -21,6 +22,13 @@ ENV HELM_VERSION=3.16.3 \
     PYTHONUTF8=1
 
 USER root
+
+# Create sterling user first
+RUN useradd -u 1010 -g 0 -m -d /app-root -s /bin/bash -c "Sterling user" sterling && \
+    install -d -m 2775 -o sterling -g root /app-root && \
+    echo 'export LANG=en_US.UTF-8' >> /app-root/.bashrc && \
+    echo 'export LC_ALL=en_US.UTF-8' >> /app-root/.bashrc && \
+    echo 'export LC_CTYPE=en_US.UTF-8' >> /app-root/.bashrc
 
 # Install system dependencies and locale support
 RUN dnf install -y jq git java-21-openjdk-headless wget unzip tar gzip glibc-all-langpacks glibc-langpack-en && \
@@ -54,16 +62,20 @@ RUN cd /tmp && \
     #ibmcloud version && \
     #rclone version
 
-# Install Ansible collections, fix permissions and cleanup
+# Install Ansible collections and cleanup
 RUN ansible-galaxy collection install kubernetes.core community.general && \
-    # Fix permissions for default user
-    bash -x /tmp/install/fix_permissions.sh && \
+    # Fix permissions for directories created during installation
+    chown -R sterling:0 /app-root/.bluemix /app-root/.ansible/tmp /app-root/.config /app-root/.ibm-pak 2>/dev/null || true && \
     # Clean up
     rm -rf /tmp/install /tmp/* /var/tmp/* /root/.cache /root/.ansible && \
-    rm -rf /usr/share/doc/* /usr/share/man/* /usr/share/info/*
+    rm -rf /usr/share/doc/* /usr/share/man/* /usr/share/info/* && \
+    #find /usr/share/locale -mindepth 1 -maxdepth 1 ! -name 'en*' -exec rm -rf {} + && \
+    find /usr/lib64/python3.12 -name "*.pyc" -delete && \
+    find /usr/lib64/python3.12 -name "*.pyo" -delete && \
+    find /usr/lib64/python3.12 -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true
 
-# Switch to default user and clone ansible-ibm-sterling repository
-USER 1001
-WORKDIR /opt/app-root/src
+# Clone ansible-ibm-sterling repository
+USER sterling
+WORKDIR /app-root
 RUN git clone https://github.com/ibm-sterling-devops/ansible-ibm-sterling.git
 CMD ["/bin/bash"]
